On node 20 we have webpacker error so we switched to es6
ROR in ./node_modules/trk_datatables/fontello/font/fontello.woff2?69212391
Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at getHashDigest (/Volumes/ONETB/dule/xceednet/node_modules/file-loader/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /Volumes/ONETB/dule/xceednet/node_modules/file-loader/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/Volumes/ONETB/dule/xceednet/node_modules/file-loader/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/Volumes/ONETB/dule/xceednet/node_modules/file-loader/dist/index.js:29:48)
 @ ./node_modules/trk_datatables/fontello/css/fontello.css
 @ ./node_modules/trk_datatables/src/index.js
 @ ./app/javascript/packs/application.js